// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	materials "github.com/Kelompok14-LMS/backend-go/businesses/materials"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: materialDomain
func (_m *Repository) Create(materialDomain *materials.Domain) error {
	ret := _m.Called(materialDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(*materials.Domain) error); ok {
		r0 = rf(materialDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: materialId
func (_m *Repository) Delete(materialId string) error {
	ret := _m.Called(materialId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(materialId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Deletes provides a mock function with given fields: moduleId
func (_m *Repository) Deletes(moduleId string) error {
	ret := _m.Called(moduleId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(moduleId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindById provides a mock function with given fields: materialId
func (_m *Repository) FindById(materialId string) (*materials.Domain, error) {
	ret := _m.Called(materialId)

	var r0 *materials.Domain
	if rf, ok := ret.Get(0).(func(string) *materials.Domain); ok {
		r0 = rf(materialId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*materials.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(materialId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: materialId, materialDomain
func (_m *Repository) Update(materialId string, materialDomain *materials.Domain) error {
	ret := _m.Called(materialId, materialDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *materials.Domain) error); ok {
		r0 = rf(materialId, materialDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
