// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	mentee_assignments "github.com/Kelompok14-LMS/backend-go/businesses/menteeAssignments"
	mock "github.com/stretchr/testify/mock"

	pkg "github.com/Kelompok14-LMS/backend-go/pkg"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: assignmentDomain
func (_m *Usecase) Create(assignmentDomain *mentee_assignments.Domain) error {
	ret := _m.Called(assignmentDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(*mentee_assignments.Domain) error); ok {
		r0 = rf(assignmentDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: assignmentId
func (_m *Usecase) Delete(assignmentId string) error {
	ret := _m.Called(assignmentId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(assignmentId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByAssignmentId provides a mock function with given fields: assignmentId, pagination
func (_m *Usecase) FindByAssignmentId(assignmentId string, pagination pkg.Pagination) (*pkg.Pagination, error) {
	ret := _m.Called(assignmentId, pagination)

	var r0 *pkg.Pagination
	if rf, ok := ret.Get(0).(func(string, pkg.Pagination) *pkg.Pagination); ok {
		r0 = rf(assignmentId, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkg.Pagination)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, pkg.Pagination) error); ok {
		r1 = rf(assignmentId, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: assignmentId
func (_m *Usecase) FindById(assignmentId string) (*mentee_assignments.Domain, error) {
	ret := _m.Called(assignmentId)

	var r0 *mentee_assignments.Domain
	if rf, ok := ret.Get(0).(func(string) *mentee_assignments.Domain); ok {
		r0 = rf(assignmentId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mentee_assignments.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(assignmentId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByMenteeId provides a mock function with given fields: menteeId
func (_m *Usecase) FindByMenteeId(menteeId string) ([]mentee_assignments.Domain, error) {
	ret := _m.Called(menteeId)

	var r0 []mentee_assignments.Domain
	if rf, ok := ret.Get(0).(func(string) []mentee_assignments.Domain); ok {
		r0 = rf(menteeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]mentee_assignments.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(menteeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: assignmentId, assignmentDomain
func (_m *Usecase) Update(assignmentId string, assignmentDomain *mentee_assignments.Domain) error {
	ret := _m.Called(assignmentId, assignmentDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *mentee_assignments.Domain) error); ok {
		r0 = rf(assignmentId, assignmentDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecase(t mockConstructorTestingTNewUsecase) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
