// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	mentee_progresses "github.com/Kelompok14-LMS/backend-go/businesses/menteeProgresses"
	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Add provides a mock function with given fields: menteeProgressDomain
func (_m *Usecase) Add(menteeProgressDomain *mentee_progresses.Domain) error {
	ret := _m.Called(menteeProgressDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(*mentee_progresses.Domain) error); ok {
		r0 = rf(menteeProgressDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecase(t mockConstructorTestingTNewUsecase) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
