// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	mentee_courses "github.com/Kelompok14-LMS/backend-go/businesses/menteeCourses"
	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// CheckEnrollment provides a mock function with given fields: menteeId, courseId
func (_m *Usecase) CheckEnrollment(menteeId string, courseId string) (bool, error) {
	ret := _m.Called(menteeId, courseId)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(menteeId, courseId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(menteeId, courseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Enroll provides a mock function with given fields: menteeCourseDomain
func (_m *Usecase) Enroll(menteeCourseDomain *mentee_courses.Domain) error {
	ret := _m.Called(menteeCourseDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(*mentee_courses.Domain) error); ok {
		r0 = rf(menteeCourseDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindMenteeCourses provides a mock function with given fields: menteeId, title, status
func (_m *Usecase) FindMenteeCourses(menteeId string, title string, status string) (*[]mentee_courses.Domain, error) {
	ret := _m.Called(menteeId, title, status)

	var r0 *[]mentee_courses.Domain
	if rf, ok := ret.Get(0).(func(string, string, string) *[]mentee_courses.Domain); ok {
		r0 = rf(menteeId, title, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]mentee_courses.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(menteeId, title, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecase(t mockConstructorTestingTNewUsecase) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
