// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	reviews "github.com/Kelompok14-LMS/backend-go/businesses/reviews"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: reviewDomain
func (_m *Repository) Create(reviewDomain *reviews.Domain) error {
	ret := _m.Called(reviewDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(*reviews.Domain) error); ok {
		r0 = rf(reviewDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByCourse provides a mock function with given fields: courseId
func (_m *Repository) FindByCourse(courseId string) ([]reviews.Domain, error) {
	ret := _m.Called(courseId)

	var r0 []reviews.Domain
	if rf, ok := ret.Get(0).(func(string) []reviews.Domain); ok {
		r0 = rf(courseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reviews.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(courseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
