// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	reviews "github.com/Kelompok14-LMS/backend-go/businesses/reviews"
	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: reviewDomain
func (_m *Usecase) Create(reviewDomain *reviews.Domain) error {
	ret := _m.Called(reviewDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(*reviews.Domain) error); ok {
		r0 = rf(reviewDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByCourse provides a mock function with given fields: courseId
func (_m *Usecase) FindByCourse(courseId string) ([]reviews.Domain, error) {
	ret := _m.Called(courseId)

	var r0 []reviews.Domain
	if rf, ok := ret.Get(0).(func(string) []reviews.Domain); ok {
		r0 = rf(courseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reviews.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(courseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByMentee provides a mock function with given fields: menteeId, title
func (_m *Usecase) FindByMentee(menteeId string, title string) ([]reviews.Domain, error) {
	ret := _m.Called(menteeId, title)

	var r0 []reviews.Domain
	if rf, ok := ret.Get(0).(func(string, string) []reviews.Domain); ok {
		r0 = rf(menteeId, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reviews.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(menteeId, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecase(t mockConstructorTestingTNewUsecase) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
