// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	mentors "github.com/Kelompok14-LMS/backend-go/businesses/mentors"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: mentorDomain
func (_m *Repository) Create(mentorDomain *mentors.Domain) error {
	ret := _m.Called(mentorDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(*mentors.Domain) error); ok {
		r0 = rf(mentorDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields:
func (_m *Repository) FindAll() (*[]mentors.Domain, error) {
	ret := _m.Called()

	var r0 *[]mentors.Domain
	if rf, ok := ret.Get(0).(func() *[]mentors.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]mentors.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *Repository) FindById(id string) (*mentors.Domain, error) {
	ret := _m.Called(id)

	var r0 *mentors.Domain
	if rf, ok := ret.Get(0).(func(string) *mentors.Domain); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mentors.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIdUser provides a mock function with given fields: userId
func (_m *Repository) FindByIdUser(userId string) (*mentors.Domain, error) {
	ret := _m.Called(userId)

	var r0 *mentors.Domain
	if rf, ok := ret.Get(0).(func(string) *mentors.Domain); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mentors.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, mentorDomain
func (_m *Repository) Update(id string, mentorDomain *mentors.Domain) error {
	ret := _m.Called(id, mentorDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *mentors.Domain) error); ok {
		r0 = rf(id, mentorDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
