// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	courses "github.com/Kelompok14-LMS/backend-go/businesses/courses"
	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: courseDomain
func (_m *Usecase) Create(courseDomain *courses.Domain) error {
	ret := _m.Called(courseDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(*courses.Domain) error); ok {
		r0 = rf(courseDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: courseId
func (_m *Usecase) Delete(courseId string) error {
	ret := _m.Called(courseId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(courseId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: keyword
func (_m *Usecase) FindAll(keyword string) (*[]courses.Domain, error) {
	ret := _m.Called(keyword)

	var r0 *[]courses.Domain
	if rf, ok := ret.Get(0).(func(string) *[]courses.Domain); ok {
		r0 = rf(keyword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]courses.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(keyword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByCategory provides a mock function with given fields: categoryId
func (_m *Usecase) FindByCategory(categoryId string) (*[]courses.Domain, error) {
	ret := _m.Called(categoryId)

	var r0 *[]courses.Domain
	if rf, ok := ret.Get(0).(func(string) *[]courses.Domain); ok {
		r0 = rf(categoryId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]courses.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(categoryId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: courseId
func (_m *Usecase) FindById(courseId string) (*courses.Domain, error) {
	ret := _m.Called(courseId)

	var r0 *courses.Domain
	if rf, ok := ret.Get(0).(func(string) *courses.Domain); ok {
		r0 = rf(courseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*courses.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(courseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByMentor provides a mock function with given fields: mentorId
func (_m *Usecase) FindByMentor(mentorId string) (*[]courses.Domain, error) {
	ret := _m.Called(mentorId)

	var r0 *[]courses.Domain
	if rf, ok := ret.Get(0).(func(string) *[]courses.Domain); ok {
		r0 = rf(mentorId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]courses.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(mentorId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: courseId, courseDomain
func (_m *Usecase) Update(courseId string, courseDomain *courses.Domain) error {
	ret := _m.Called(courseId, courseDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *courses.Domain) error); ok {
		r0 = rf(courseId, courseDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecase(t mockConstructorTestingTNewUsecase) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
