name: Run CI CD Development for Backend Application Eduworld

on:
  push:
    branches:
      - 'development'

jobs:
  testing:
    runs-on: ubuntu-latest
    name: 'Run unit test and linter'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: 'Run unit test'
        run: go test -v ./...
      - name: 'Run linter with golangci-lint'
        uses: golangci/golangci-lint-action@v3

  build:
    runs-on: ubuntu-latest
    name: 'Run golang build'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: 'Build go application'
        run: go build -o ./dist/main .

  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE: eduworld/eduworld
    name: 'Run automation deployment to Digital Ocean Droplet'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Setup QEMU
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE }}:${{ github.sha }}-${{ github.run_number }}

      - name: Login to Droplet via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOSTNAME }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            docker stop eduworld-app
            docker container rm eduworld-app
            docker pull ${{ env.IMAGE }}:${{ github.sha }}-${{ github.run_number }}
            cd eduworld
            docker container create --name eduworld-app -p 80:8080 -e GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GCP_KEY }} ${{ env.IMAGE }}:${{ github.sha }}-${{ github.run_number }}
            docker cp $PWD/.env eduworld-app:/.env
            docker cp $PWD/gcp_key.json eduworld-app:/gcp_key.json
            docker start eduworld-app
